name: Design Token CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/figma-token/**
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¦ Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: âš™ï¸ Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: ðŸ’¾ Get pnpm store directory
        id: pnpm-store-dir-path
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: ðŸ“¥ Setup pnpm cache
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: ðŸ“¦ Install dependencies
        run: pnpm install --filter "@moeum/figma-token" --no-frozen-lockfile

      - name: ðŸ› ï¸ Build token files
        run: pnpm run build:figma-token

      - name: ðŸ“‚ Create Token Directory
        run: mkdir -p packages/moeum-components/style/design-token

      - name: ðŸ“‹ Copy CSS files
        run: |
          cp packages/figma-token/build/css/*.css packages/moeum-components/style/design-token/

      - name: ðŸš€ Generate Token Index
        run: |
          # íŒŒì¼ ì´ˆê¸°í™”
          > packages/moeum-components/style/design-token/index.scss

          # design-token í´ë”ì˜ ëª¨ë“  CSS íŒŒì¼ì„ ì°¾ì•„ì„œ @use êµ¬ë¬¸ ìƒì„±
          for file in packages/moeum-components/style/design-token/*.css; do
            filename=$(basename "$file")
            echo "@use \"./${filename}\";" >> packages/moeum-components/style/design-token/index.scss
          done

      - name: ðŸš€ Commit and push changes
        run: |
          git config --local user.email "moeum[bot]@users.noreply.github.com"
          git config --local user.name "moeum[bot]"

          git add packages/moeum-components/style/design-token/
          git commit -m "ðŸŽ¨ chore: Update design token files" || echo "No changes to commit"
          git push origin ${{ github.ref }}
